### ISSUE TITLE
How this is gonna be synced with Docker bench security

### ISSUE THREAD

**Issue by mcvidanagama** [gaia-adm/docker-bench-test#3]
Hi,

Suppose that docker bench security added a new test. 
How are we gonna get that newly added test in to this docker-bench-test ?

Regards,
Mahesh

**Comment by alexei-led** [comment]
I see 3 options:
1) I plan to update project with new tests from time to time
2) Anyone can report a GitHub issue with missing or not working test and I will fix
3) Anyone can add missing test and submit a GitHub Pull Request and I will check and merge

It's an open source project, so any option is open too :)

**Comment by mcvidanagama** [comment]
Hi,
Thanks for the answer.
